spring:
  application:
    name: recipe-service
  cloud:
    enabled: false
    consul:
      enabled: false
      # host: consul
      host: localhost
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        register: false
        instance-id: recipe-service-${server.port}
        service-name: recipe-service
        health-check-path: /actuator/health
        health-check-interval: 10s
  datasource:
    # url: jdbc:mysql://zaboradb.mysql.database.azure.com:3306/recipe_service?sslMode=REQUIRED&allowPublicKeyRetrieval=true
    # username: zabora
    # password: z@bora08
    url: jdbc:mysql://localhost:3306/recipe_service?sslMode=REQUIRED&allowPublicKeyRetrieval=true
    username: root
    password: 2006
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8001

management:
  endpoints:
    web:
      exposure:
        include: health,info